Original file line number	Original file line	Diff line number	Diff line change
	@@ -1,7 +1,7 @@
name: Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: main



	@@ -21,15 +21,16 @@ jobs:
      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: rc


      - name: Build step
        working-directory: ./www
        run: "deno task build" # ğŸ“ Update the build command(s) if necessary


      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "fresh" # ğŸ“ Update the deploy project name if necessary
          entrypoint: "./www/main.ts" # ğŸ“ Update the entrypoint if necessary
          root: "."